CREATE DATABASE IF NOT EXISTS camagru 
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE camagru;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    is_verified BOOLEAN DEFAULT FALSE,
    token VARCHAR(255) NULL
);